### ISSUE TITLE
Add GitInformation to file headers

### ISSUE THREAD

**Issue by malankriel** [VirtualActuary/zebra-vba-packager#10]
# Background

Similar to #5, we need to know which git tag, version and commit relates to a version of the Zebra files.

For some inspiration: https://github.com/AutoActuary/runner-engine/blob/478c151ec6a5708ba2f9e481b838170689b1b4da/tools/deploy-scripts/tools/activate-gitinfo.py. Generates this:
![image](https://user-images.githubusercontent.com/51300197/156046144-48031ba1-c712-49d8-ad36-cd54799940d9.png)
The following info is stored:
 - `commit`
 - `repo`
 - `datetime` (less important I guess)
 - `tag`: what if not exactly on tag? then blank / null?
 - `branch`: branch pulled (less important I guess?)
 - `version`
 - `path`: can't figure this one out? maybe the path to the file within the git repo? But what if we combine files?
 - `vbapath`: not sure why?

## Questions

- do we keep it in the JSON format? I would say no, rather normal commented code (or maybe YAML if it looks neat)
- do we want the constants at the top? Discussed in approaches below.

# Approach

I think there are two parts to this (1) when we source files from a git repo and (2) when we compile a workbook within a git repo.

## Source files from a git repo

- This is something that is local to a specific .bas or .cls file (where does this file come from)
- This will only be in .bas files imported into a project, and not the files that lives in a project. So the header only changes when the version it imports changes.
- When sourcing files from a git repo, automatically add a header with the git information data
- I might argue to add the git-information as private constants:
   - Then we can call these within the sub if we need to, for example report the version in a run log, results report, etc, etc
   - Maybe have a flag on whether to include this, with default true?
```
Private Const zGIT_COMMIT As String = "2f3204166e3605f134913fb092ad855261e91c30"
Private Const zGIT_REPO As String = "git@github.com:AutoActuary/runner-engine.git"
Private Const zGIT_DATETIME As String = "2021-04-03 14:46:25 +0200"
Private Const zGIT_TAG As String = "v1.14.2"
Private Const zGIT_BRANCH As String = "master"
Private Const zGIT_VERSION As String = "v1.14.2-dirty"
Private Const zGIT_PATH As String = "None"
Private Const zGIT_VBAPATH As String = "RunnerInputs"
```

## Compiling a workbook within a repo

- This is something that is local to a specific workbook (where does this workbook come from)?
- Something similar to https://github.com/AutoActuary/runner-engine/blob/478c151ec6a5708ba2f9e481b838170689b1b4da/tools/deploy-scripts/tools/activate-gitinfo.py can be used here
- Have a specific module that specifies the git info of where the workbook was compiled.
- These are typically more custom and can be built in the `./compile.py` setup. Just need to make sure we have everything we need from the above in zebra.

**Comment by heetbeet** [comment]
I would also want to use the minimum number of parameters to represent the source of the file. Basically like only using the git repo and the tag+delta.

I think this should be kept as short as possible and be at the top of each zebra imported file. If we import a module from somewhere that already has zebra imported modules, then the imported-imported module should keep its original source location information (i.e. the true source of files should be kept). Then it's easier to investigate where individual files come from. 

I.e., given a structure where the user has written a new file, imported `Fn` and `LibAAA` and as a side-effect/dependency got `LibAAADependency`:
```
NewlyWritten.bas
z__NameSpaces.bas
z__Fn.cls
z__LibAAA.cls
z__LibAAADependency.cls
```
I would expect the files to contain comments like:
- `NewlyWritten.bas` (no comment)
- `z__NameSpaces.bas` (no comment, auto generated file)
- `z__Fn.cls`:  `'zebra Source git@github.com:Company/Fn.git v1.11.5-10-g9ed6d7e`
- `z__LibAAA.cls`: `'zebra Source git@github.com:LibAAA/LibAAA.git v0.0.1-5-adf45da1`
- `z__LibAAADependency.cls`: `'zebra Source git@github.com:LibAAADependancy/LibAAADependancy.git v0.1.2-5-dfad123` (kept original LibAAA annotation)

But then you still cannot use it for any programmatic version checking etc. So maybe after we establish this, we can move over to what should be done to accomplish that.

**Comment by malankriel** [comment]
> I would also want to use the minimum number of parameters to represent the source of the file. Basically like only using the git repo and the tag+delta.
> 
> I think this should be kept as short as possible and be at the top of each zebra imported file. If we import a module from somewhere that already has zebra imported modules, then the imported-imported module should keep its original source location information (i.e. the true source of files should be kept). Then it's easier to investigate where individual files come from.
> 
> I.e., given a structure where the user has written a new file, imported `Fn` and `LibAAA` and as a side-effect/dependency got `LibAAADependency`:
> 
> ```
> NewlyWritten.bas
> z__NameSpaces.bas
> z__Fn.cls
> z__LibAAA.cls
> z__LibAAADependency.cls
> ```
> 
> I would expect the files to contain comments like:
> 
> * `NewlyWritten.bas` (no comment)
> * `z__NameSpaces.bas` (no comment, auto generated file)
> * `z__Fn.cls`:  `'zebra Source git@github.com:Company/Fn.git v1.11.5-10-g9ed6d7e`
> * `z__LibAAA.cls`: `'zebra Source git@github.com:LibAAA/LibAAA.git v0.0.1-5-adf45da1`
> * `z__LibAAADependency.cls`: `'zebra Source git@github.com:LibAAADependancy/LibAAADependancy.git v0.1.2-5-dfad123` (kept original LibAAA annotation)
> 
> But then you still cannot use it for any programmatic version checking etc. So maybe after we establish this, we can move over to what should be done to accomplish that.

Yes, I think any type of annotation would be great to just be able to eye-ball which version a user have on their side?
