### ISSUE TITLE
Namespacing multiple bas files from a source

### ISSUE THREAD

**Issue by heetbeet** [VirtualActuary/zebra-vba-packager#2]
When namespacing multiple `.bas` files and they rely on each other, then the new namespaced name doesn't get replaced in the other namespaced files. I.e. we can currently only namespace single `.bas` files

**Comment by heetbeet** [comment]
This is partly why I flatten the files in the following library:
https://github.com/AutoActuary/TemplateGenerator/blob/c479011a770fe0985b2e554c30e3603be72acf05/scripts/compile.py#L48

**Comment by heetbeet** [comment]
Hmm... flattening is quite useful in any case. Maybe we should support it...

**Comment by malankriel** [comment]
Blocked by #9. We can easily do this when we have #9 built in.

**Comment by heetbeet** [comment]
https://github.com/VirtualActuary/zebra-vba-packager/releases/tag/0.0.8
