### ISSUE TITLE
Declared variables within a module should be moved to the top of the module

### ISSUE THREAD

**Issue by malankriel** [VirtualActuary/zebra-vba-packager#36]
See the compile.cmd in MiscVBA as an example where `Public fso as filesystemobject` is in the middle of the module instead of at the top. 

![image](https://user-images.githubusercontent.com/51300197/182635286-0ec9a883-3bb2-4fd0-ae0d-e843fa352417.png)

![image](https://user-images.githubusercontent.com/51300197/182635330-c31ca16f-9f76-4bac-b8b7-f24c6118889e.png)

**Comment by heetbeet** [comment]
This one is easier than #36 , so although lower priority, I'm gonna start here to get into things

**Comment by heetbeet** [comment]
This is ending up way more difficult than expected. Basically, the "join-into-single-bas-file" works for all our use-cases by pure luck. There is quite a big error in the code, and removing the error brings up another error that cannot easily be fixed. This is stalling a bunch of other progress I want to make on zebra, so I'll have to focus on cleaning up this mess.

**Comment by heetbeet** [comment]
https://github.com/VirtualActuary/zebra-vba-packager/pull/40
