### ISSUE TITLE
Encoding error

### ISSUE THREAD

**Issue by malankriel** [VirtualActuary/zebra-vba-packager#37]
In the AllLife forecasting model, we get this:

![image](https://user-images.githubusercontent.com/51300197/182637747-96390c9f-d019-4374-9955-7291a7beac85.png)

Which sometimes changes to this in VBA:

![image](https://user-images.githubusercontent.com/51300197/182637895-3abeed3a-6f90-467e-9846-e759527aebec.png)

**Comment by heetbeet** [comment]
Seems to already be a problem at the source:
https://github.com/VirtualActuary/TemplateGenerator/blob/d07981617f8a7524aae3d107f46af0f2fab6142f/TemplateGenerator/z_WsCsvSniffer.cls#L141

**Comment by heetbeet** [comment]
But was correct at the source-source:
https://github.com/VirtualActuary/VBALib/blob/8a56d002e3e2e82facec78d5339ed4b522e80c69/VBALib/z_WsCsvSniffer.cls#L141

**Comment by malankriel** [comment]
> But was correct at the source-source: https://github.com/VirtualActuary/VBALib/blob/8a56d002e3e2e82facec78d5339ed4b522e80c69/VBALib/z_WsCsvSniffer.cls#L141

Okay, so we should fix it in the VBALib where we are importing this from?

**Comment by heetbeet** [comment]
Last one on the list...

**Comment by heetbeet** [comment]
https://github.com/ws-garcia/VBA-CSV-interface/blob/48226feb4df3090961e386ec9d712779b85a2e8d/src/CSVSniffer.cls#L141

**Comment by heetbeet** [comment]
Fixed by using latin-1 as the main encoder for decoding and encoding in zebra-vba
