### ISSUE TITLE
Add zebra metadata to the file headers

### ISSUE THREAD

**Issue by heetbeet** [VirtualActuary/zebra-vba-packager#5]
Add a way for us to know if a file has been generated with zebra packager

**Comment by malankriel** [comment]
Some nice art to include:
https://ascii.co.uk/art/zebra

I like these two:

```
    \\/),
   ,'.' /,
  (_)- / /,
     /\_/ |__..--,  *
    (\___/\ \ \ / ).'
     \____/ / (_ //
      \\_ ,'--'\_(
      )_)_/ )_/ )_)
     (_(_.'(_.'(_.'
```

or a bit fewer lines:

```
       _,,
      "-.\=
         \\=   _.~
        _|/||||)_
        \        \
```

**Comment by BartJan142** [comment]
This is a bit heavy-handed. We already have a solution to add git info to file headers. That should be enough to show that a file has been imported from an external source.
