### ISSUE TITLE
Git repos in temp directory gets corrupted

### ISSUE THREAD

**Issue by Andre-Erasmus** [VirtualActuary/zebra-vba-packager#7]
The following error occurred when trying to replace the vba of an .xlsb file:
![image](https://user-images.githubusercontent.com/82467559/133029392-5f76f687-c88e-4a5e-8be0-6f9166329a88.png)

The fix for the issue was to clear the temp folders.

**Comment by heetbeet** [comment]
https://github.com/VirtualActuary/zebra-vba-packager/pull/16
