### ISSUE TITLE
Enforce casing

### ISSUE THREAD

**Issue by malankriel** [VirtualActuary/zebra-vba-packager#8]
Enforce casing on compile / decompiling of scripts. 

@heetbeet do we want to allow for a list of names that should be used / overwritten?

My suggestion is to use the same conventions as in VBA, ie PascalCase?

Does that mean we use `I` instead of `i`? And `Wb` instead of `WB`?

**Comment by heetbeet** [comment]
According to c# definition of Pascal case, two letter acronyms are written in upper case (WB) three or more gets camelled (Json, ToHtml). But it might be too difficult to automatically sniff out when something is an acronym. So probably best to use Wb

**Comment by malankriel** [comment]
> According to c# definition of Pascal case, two letter acronyms are written in upper case (WB) three or more gets camelled (Json, ToHtml). But it might be too difficult to automatically sniff out when something is an acronym. So probably best to use Wb

I would prefer to stay with the strict definition as a lot of this will be driven by how we define the variables? And I can't think of two-letter words used that's not an acronym?

**Comment by malankriel** [comment]
Three options:
 - `Pascal`
 - `camel`
 - `ignore` / none (default)


API:
 - When sourcing Zebra files
 - Run on Glob of files after exporting VBA files

"varchoice" / mechanism to override specific variables


NB: Do not change casing for DLL API variables ("ptrSafe")

**Comment by malankriel** [comment]
This does it for the `camelCase` option: https://github.com/AutoActuary/autory/blob/master/tools/deploy-scripts/tools/enforce-vba-case.py

Good starting point and use similar conventions. Use the Zebra tokeniser, etc
